name: 'Migrations folder linter'
description: 'This github action validates if the prisma migration folders follow a set naming structure'
inputs:
  path:
    description: 'The path to the migrations directory'
    required: true
    default: './prisma/migrations/'
  ignore:
    description: 'A list of migration names to ignore'
    required: true
outputs:
  total-files-analyzed:
    description: 'The number of files analyzed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
