name: 'Migrations folder linter'
description: 'This github action validates if the prisma migration folders follow a set naming structure'
inputs:
  path:
    description: 'The path to a directory to check the filenames.'
    required: true
    default: './'
  pattern:
    description: 'The regex pattern to match for each of the files in the given directory'
    required: true
    default: '/.+/'
outputs:
  total-files-analyzed:
    description: 'The number of files analyzed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
