name: 'Lint Prisma migrations action'
description: 'Goes through all Prisma migrations and ensures that the migration names match a standard format and have a valid date prefix'
branding:
  icon: 'database'
  color: 'green'
inputs:
  path:
    description: 'The path to the prisma migrations directory'
    required: false
    default: './prisma/migrations/'
  ignore:
    description: 'A list of migration names to ignore'
    required: false
  rules:
    description: 'The list of rules you would like to run'
    required: false
outputs:
  total-files-analyzed:
    description: 'The number of files analyzed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
