name: 'test'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NODE_VERSION: '22.16.0'
  PNPM_VERSION: '10.7.0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests folders that should work
        uses: ./
        with:
          path: './stubs'

      - name: Tests folders are ignored
        uses: ./
        with:
          path: './stubs'
          ignore: |
            20250101000000_should_work
            20240101000000_should_also_work
