name: 'test'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test-prisma-migration-folders
        uses: ./
        with:
          path: './__tests__/test-files/02-name-dot-extension-files'
