name: 'test'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests folders that should work
        uses: ./
        with:
          path: './demo/works'

      - name: Tests folders that should not work but are ignored
        uses: ./
        with:
          path: './demo/fails'
          ignore: |
            20260101000000_should_also_not_work
            20270101000000_should_not_work
