name: 'test'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests folders that should work
        uses: ./
        with:
          path: './tests/works'

      - name: Tests folders that should not work
        uses: ./
        with:
          path: './tests/fails'
